import React, { useState, useEffect, useRef } from 'react';
import { Sparkles, Trash2, Download, Eye, EyeOff, X, Check, FileText } from 'lucide-react';

interface FeedbackPin {
  id: string;
  page: string;
  x: number; // percentage of viewport width
  y: number; // percentage of viewport height
  selector: string;
  elementText: string;
  text: string;
  createdAt: string;
}

interface FeedbackOverlayProps {
  activePage: string;
}

function getUniqueSelector(el: HTMLElement): string {
  if (!el) return '';
  if (el.id) return `#${el.id}`;
  
  let path: string[] = [];
  let current: HTMLElement | null = el;
  while (current && current !== document.body) {
    let selector = current.tagName.toLowerCase();
    
    if (current.className) {
      // Remove class names generated by feedback overlay itself or active styles
      const classes = current.className
        .split(/\s+/)
        .filter(c => c && 
          !c.startsWith('feedback-') && 
          !c.includes('hover') && 
          !c.includes('active') && 
          !c.includes('transition') && 
          !c.includes('duration') && 
          !c.includes('outline')
        );
      if (classes.length > 0) {
        selector += '.' + classes.slice(0, 2).join('.');
      }
    }
    
    path.unshift(selector);
    current = current.parentElement;
  }
  return path.join(' > ');
}

function getFriendlyElementName(el: HTMLElement): string {
  if (!el) return '未知元素';
  
  const text = el.innerText?.trim();
  
  if (el.tagName === 'BUTTON' || el.closest('button')) {
    const btnText = el.closest('button')?.innerText?.trim() || text;
    return `按钮 [${btnText ? btnText.slice(0, 20) : '未命名'}]`;
  }
  
  if (el.tagName === 'A' || el.closest('a')) {
    const aText = el.closest('a')?.innerText?.trim() || text;
    return `链接 [${aText ? aText.slice(0, 20) : '未命名'}]`;
  }
  
  if (el.tagName === 'INPUT') {
    const input = el as HTMLInputElement;
    return `输入框 [${input.placeholder || input.name || '文本框'}]`;
  }
  
  if (/^H[1-6]$/.test(el.tagName)) {
    return `标题 [${text ? text.slice(0, 15) : el.tagName}]`;
  }
  
  if (el.tagName === 'TH') {
    return `表头 [${text ? text.slice(0, 15) : '列'}]`;
  }
  
  if (el.tagName === 'TD') {
    const ths = el.closest('table')?.querySelectorAll('th');
    const cellIdx = Array.from(el.parentElement?.children || []).indexOf(el);
    const colName = ths && ths[cellIdx] ? (ths[cellIdx] as HTMLElement).innerText.trim() : '';
    return `表格单元格 [${colName ? colName + ': ' : ''}${text ? text.slice(0, 15) : ''}]`;
  }
  
  if (text) {
    return `${el.tagName.toLowerCase()} [${text.slice(0, 20)}...]`;
  }
  
  return el.tagName.toLowerCase();
}

export const FeedbackOverlay: React.FC<FeedbackOverlayProps> = ({ activePage }) => {
  const [isEnabled, setIsEnabled] = useState(false);
  const [showPins, setShowPins] = useState(true);
  const [pins, setPins] = useState<FeedbackPin[]>([]);
  const [hoveredRect, setHoveredRect] = useState<DOMRect | null>(null);
  const [hoveredElement, setHoveredElement] = useState<HTMLElement | null>(null);
  
  // State for creating a new pin
  const [activeNewPin, setActiveNewPin] = useState<{
    x: number;
    y: number;
    selector: string;
    elementText: string;
  } | null>(null);
  const [newComment, setNewComment] = useState('');
  
  const overlayRef = useRef<HTMLDivElement>(null);
  
  // Load pins from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem('zbom_feedback_pins');
    if (saved) {
      try {
        setPins(JSON.parse(saved));
      } catch (e) {
        console.error('Failed to parse feedback pins', e);
      }
    }
  }, []);
  
  // Save pins to localStorage whenever they change
  const savePins = (newPins: FeedbackPin[]) => {
    setPins(newPins);
    localStorage.setItem('zbom_feedback_pins', JSON.stringify(newPins));
  };
  
  // Reset hover/input state when page changes
  useEffect(() => {
    setHoveredRect(null);
    setHoveredElement(null);
    setActiveNewPin(null);
    setNewComment('');
  }, [activePage]);
  
  // Mousemove listener for element selection
  useEffect(() => {
    if (!isEnabled || activeNewPin) {
      setHoveredRect(null);
      setHoveredElement(null);
      return;
    }
    
    const handleMouseMove = (e: MouseEvent) => {
      if (!overlayRef.current) return;
      
      // Temporarily disable overlay pointer events to probe underneath
      overlayRef.current.style.pointerEvents = 'none';
      const target = document.elementFromPoint(e.clientX, e.clientY) as HTMLElement | null;
      overlayRef.current.style.pointerEvents = 'auto';
      
      if (!target || target === document.body || target === document.documentElement) {
        setHoveredRect(null);
        setHoveredElement(null);
        return;
      }
      
      // Ignore elements inside the feedback UI itself
      if (target.closest('.feedback-ignore')) {
        setHoveredRect(null);
        setHoveredElement(null);
        return;
      }
      
      const rect = target.getBoundingClientRect();
      setHoveredRect(rect);
      setHoveredElement(target);
    };
    
    window.addEventListener('mousemove', handleMouseMove);
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
    };
  }, [isEnabled, activeNewPin]);
  
  // Handle click on the overlay to add a pin
  const handleOverlayClick = (e: React.MouseEvent) => {
    if (!isEnabled || activeNewPin || !hoveredElement) return;
    
    e.preventDefault();
    e.stopPropagation();
    
    const selector = getUniqueSelector(hoveredElement);
    const friendlyName = getFriendlyElementName(hoveredElement);
    
    setActiveNewPin({
      x: e.clientX,
      y: e.clientY,
      selector,
      elementText: friendlyName
    });
    setNewComment('');
  };
  
  const handleSavePin = () => {
    if (!activeNewPin || !newComment.trim()) return;
    
    const newPin: FeedbackPin = {
      id: 'pin_' + Date.now(),
      page: activePage,
      // Store relative coordinate percentages for responsiveness
      x: (activeNewPin.x / window.innerWidth) * 100,
      y: (activeNewPin.y / window.innerHeight) * 100,
      selector: activeNewPin.selector,
      elementText: activeNewPin.elementText,
      text: newComment.trim(),
      createdAt: new Date().toLocaleString()
    };
    
    savePins([...pins, newPin]);
    setActiveNewPin(null);
    setNewComment('');
  };
  
  const handleDeletePin = (id: string) => {
    const updated = pins.filter(p => p.id !== id);
    savePins(updated);
  };
  
  const handleClearAll = () => {
    if (window.confirm('确定要清空所有当前页面的标注吗？')) {
      const updated = pins.filter(p => p.page !== activePage);
      savePins(updated);
    }
  };
  
  const handleExportMarkdown = () => {
    const pagePins = pins.filter(p => p.page === activePage);
    if (pagePins.length === 0) {
      alert('当前页面暂无标注，请先点击界面元素添加改善意见！');
      return;
    }
    
    const pageNames: Record<string, string> = {
      'dashboard': 'Dashboard 总览看板',
      'bom': 'BOM Editor 主编辑工作区',
      'product-matrix': 'Product Matrix Center 产品矩阵中心',
      'ebom-architecture': 'EBOM Architecture Workspace 工程BOM架构区',
      'mbom-delta': 'MBOM Delta Console 制造BOM差异控制台',
      'tooling': 'Tooling Hub 模具/工装中心',
      'eco': 'ECO Manager 工程变更管理',
      'compare': 'BOM Compare 版本比对',
      'parts': 'Part Library 料库管理',
      'suppliers': 'Supply Chain Intelligence 供应链情报',
    };
    
    const pageTitle = pageNames[activePage] || activePage;
    let md = `# zBOM 系统 - [${pageTitle}] UI与功能改善期望清单\n`;
    md += `> **生成时间**: ${new Date().toLocaleString()} (客户端本地持久化暂存数据)\n\n`;
    md += `---\n\n`;
    md += `## 📂 当前页面标注列表 (${pagePins.length} 个改进点)\n\n`;
    
    pagePins.forEach((pin, idx) => {
      md += `### 📍 改善点 #${idx + 1}\n`;
      md += `- **定位元素**: \`${pin.elementText}\`\n`;
      md += `- **CSS选择器**: \`${pin.selector}\`\n`;
      md += `- **改善要求**: **${pin.text}**\n`;
      md += `- **标注时间**: ${pin.createdAt}\n`;
      md += `- **相对坐标**: \`X: ${pin.x.toFixed(1)}%, Y: ${pin.y.toFixed(1)}%\`\n\n`;
    });
    
    md += `---\n\n`;
    md += `## 💡 AI 极速实施指南\n`;
    md += `1. **直接复制此清单**，在聊天框中发送给 Antigravity (AI 助手)。\n`;
    md += `2. AI 助手将读取每个标注的选择器和定位元素，并自动定位并批量修改相应的 React 组件。\n`;
    
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `zBOM_改善清单_${activePage}_${Date.now().toString().slice(-6)}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };
  
  const currentPagePins = pins.filter(p => p.page === activePage);
  
  return (
    <>
      {/* 1. Global Viewport Overlay (Active only when feedback is enabled) */}
      <div
        ref={overlayRef}
        className={`fixed inset-0 z-[9990] transition-colors duration-200 ${
          isEnabled ? 'bg-slate-900/10 cursor-crosshair pointer-events-auto' : 'pointer-events-none'
        }`}
        onClick={handleOverlayClick}
      >
        {/* Hover Highlight Box */}
        {isEnabled && hoveredRect && !activeNewPin && (
          <div
            className="absolute border-2 border-dashed border-blue-500 bg-blue-500/15 pointer-events-none rounded shadow-[0_0_12px_rgba(59,130,246,0.3)] transition-all duration-75"
            style={{
              top: hoveredRect.top,
              left: hoveredRect.left,
              width: hoveredRect.width,
              height: hoveredRect.height,
            }}
          >
            {/* Tiny Label in the corner */}
            <div className="absolute left-0 bottom-full mb-1 px-1.5 py-0.5 bg-blue-600 text-white text-[10px] font-mono rounded shadow-sm whitespace-nowrap">
              {hoveredElement ? getFriendlyElementName(hoveredElement) : ''}
            </div>
          </div>
        )}
        
        {/* Render Saved Pins */}
        {showPins && currentPagePins.map((pin, index) => (
          <div
            key={pin.id}
            className="absolute pointer-events-auto group feedback-ignore"
            style={{
              left: `${pin.x}%`,
              top: `${pin.y}%`,
              transform: 'translate(-50%, -50%)',
            }}
            onClick={(e) => e.stopPropagation()} // Prevent clicking parent overlay
          >
            {/* Pulsing visual circle */}
            <div className="absolute -inset-2 w-8 h-8 rounded-full bg-rose-500/35 animate-ping pointer-events-none" />
            <div className="relative w-7 h-7 rounded-full bg-gradient-to-br from-rose-500 to-rose-600 text-white flex items-center justify-center text-xs font-black shadow-md border-2 border-white hover:scale-115 transition-transform duration-150 cursor-pointer">
              {index + 1}
            </div>
            
            {/* Super premium floating card tooltip on hover */}
            <div className="absolute left-1/2 bottom-full mb-3 -translate-x-1/2 hidden group-hover:block w-72 bg-slate-950/95 border border-slate-800 p-4 rounded-xl shadow-2xl z-[9999] backdrop-blur-md text-xs text-slate-200">
              <div className="flex items-center justify-between mb-2">
                <span className="font-extrabold text-rose-400 text-sm">标注 #{index + 1}</span>
                <span className="text-[10px] text-slate-500">{pin.createdAt.split(' ')[1] || ''}</span>
              </div>
              <div className="mb-3">
                <span className="text-[10px] text-slate-400 block font-semibold mb-0.5">目标元素:</span>
                <div className="bg-slate-900 px-2 py-1 rounded font-mono text-[10px] text-slate-300 border border-slate-800 break-all select-all overflow-hidden text-ellipsis">
                  {pin.elementText}
                </div>
              </div>
              <div className="mb-3">
                <span className="text-[10px] text-slate-400 block font-semibold mb-0.5">期望改进要求:</span>
                <div className="text-slate-100 font-medium whitespace-pre-wrap text-sm leading-relaxed leading-normal bg-slate-900/50 p-2 rounded border border-slate-800/40">
                  {pin.text}
                </div>
              </div>
              <div className="flex justify-between items-center pt-2 border-t border-slate-800/80">
                <span className="text-[10px] text-slate-600">X:{pin.x.toFixed(0)}% Y:{pin.y.toFixed(0)}%</span>
                <button
                  onClick={() => handleDeletePin(pin.id)}
                  className="flex items-center gap-1 text-rose-400 hover:text-rose-300 font-bold underline transition-colors cursor-pointer"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                  删除
                </button>
              </div>
            </div>
          </div>
        ))}
        
        {/* Absolute Input card for setting active pin */}
        {activeNewPin && (
          <div
            className="absolute bg-white border border-slate-200 shadow-2xl p-4 rounded-2xl w-80 pointer-events-auto z-[9999] flex flex-col gap-3 feedback-ignore animate-in fade-in slide-in-from-bottom-4 duration-200"
            style={{
              left: Math.min(activeNewPin.x, window.innerWidth - 340),
              top: Math.min(activeNewPin.y, window.innerHeight - 240),
            }}
            onClick={(e) => e.stopPropagation()} // Prevent clicking overlay
          >
            <div className="flex items-center justify-between border-b border-slate-100 pb-2">
              <div className="flex items-center gap-1.5">
                <div className="w-2.5 h-2.5 rounded-full bg-blue-500 animate-pulse" />
                <span className="font-bold text-slate-800 text-sm">记录 UI/功能改进期望</span>
              </div>
              <button 
                onClick={() => setActiveNewPin(null)}
                className="p-1 hover:bg-slate-100 rounded-full text-slate-400 hover:text-slate-600 transition-colors"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
            
            <div className="flex flex-col gap-1">
              <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">当前选中元素</span>
              <div className="bg-slate-50 border border-slate-200 px-2 py-1.5 rounded-lg text-xs text-slate-600 font-mono break-all line-clamp-2 max-h-12 overflow-y-auto">
                {activeNewPin.elementText}
              </div>
            </div>
            
            <div className="flex flex-col gap-1">
              <label htmlFor="feedback-comment" className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">请输入您的改善期望</label>
              <textarea
                id="feedback-comment"
                value={newComment}
                onChange={(e) => setNewComment(e.target.value)}
                placeholder="例如：这里需要增加搜索筛选、样式颜色不对、数字计算滚算公式有误..."
                className="w-full min-h-[80px] p-2 border border-slate-200 rounded-lg text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                autoFocus
              />
            </div>
            
            <div className="flex justify-end gap-2 pt-1">
              <button
                onClick={() => setActiveNewPin(null)}
                className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-600 font-bold rounded-lg text-xs transition-colors cursor-pointer"
              >
                取消
              </button>
              <button
                onClick={handleSavePin}
                disabled={!newComment.trim()}
                className={`px-3 py-1.5 font-bold rounded-lg text-xs text-white transition-all flex items-center gap-1 cursor-pointer ${
                  newComment.trim() 
                    ? 'bg-blue-600 hover:bg-blue-700 shadow-md shadow-blue-500/10' 
                    : 'bg-slate-300 cursor-not-allowed'
                }`}
              >
                <Check className="w-3.5 h-3.5" />
                保存标注
              </button>
            </div>
          </div>
        )}
      </div>
      
      {/* 2. Floating Controller Panel (Always visible in bottom-right corner) */}
      <div className="fixed bottom-6 right-6 z-[9995] feedback-ignore">
        {!isEnabled ? (
          // Compact toggle FAB
          <button
            onClick={() => setIsEnabled(true)}
            className="group flex items-center gap-2 bg-gradient-to-r from-slate-800 to-slate-900 text-white pl-4 pr-5 py-3 rounded-full shadow-lg shadow-slate-900/30 hover:shadow-xl hover:shadow-slate-900/40 hover:-translate-y-0.5 transition-all duration-200 font-bold text-xs border border-slate-700/50 cursor-pointer"
          >
            <Sparkles className="w-4 h-4 text-blue-400 group-hover:animate-bounce" />
            <span>开启 UI 标注模式</span>
            {currentPagePins.length > 0 && (
              <span className="w-5 h-5 rounded-full bg-rose-500 text-white flex items-center justify-center text-[10px] font-black border border-slate-800">
                {currentPagePins.length}
              </span>
            )}
          </button>
        ) : (
          // Expanded control drawer
          <div className="backdrop-blur-md bg-white/90 border border-slate-200 shadow-2xl p-4 rounded-2xl w-80 text-sm text-slate-800 flex flex-col gap-3.5 transition-all duration-200 transform scale-100 animate-in zoom-in-95 duration-150">
            {/* Header */}
            <div className="flex items-center justify-between border-b border-slate-200/60 pb-2">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                <span className="font-extrabold text-slate-800 tracking-wide text-xs">🎨 UI 改善标注模式 (激活)</span>
              </div>
              <button 
                onClick={() => setIsEnabled(false)}
                className="p-1 hover:bg-slate-100 rounded-full text-slate-400 hover:text-slate-600 transition-colors"
                title="关闭标注"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
            
            {/* Help Prompt */}
            <div className="bg-blue-50/60 border border-blue-100/80 p-2.5 rounded-xl text-blue-700 text-xs leading-relaxed">
              💡 **操作指南**：鼠标悬停在界面任何组件上，会出现虚线框。直接**点击**即可落图钉，并记录您的改善意见。
            </div>
            
            {/* Counters */}
            <div className="grid grid-cols-2 gap-2 text-center text-xs">
              <div className="bg-slate-50 border border-slate-100 py-2 rounded-xl flex flex-col">
                <span className="text-[10px] text-slate-400 font-bold">当前页面标注</span>
                <span className="text-lg font-black text-slate-800">{currentPagePins.length}</span>
              </div>
              <div className="bg-slate-50 border border-slate-100 py-2 rounded-xl flex flex-col">
                <span className="text-[10px] text-slate-400 font-bold">系统全部标注</span>
                <span className="text-lg font-black text-slate-800">{pins.length}</span>
              </div>
            </div>
            
            {/* Pin Visibility Toggle & Clear */}
            <div className="flex items-center justify-between py-0.5 border-t border-b border-slate-100/60 text-xs">
              <button 
                onClick={() => setShowPins(!showPins)}
                className="flex items-center gap-1.5 text-slate-500 hover:text-slate-700 transition-colors font-semibold py-1.5 cursor-pointer"
              >
                {showPins ? (
                  <>
                    <EyeOff className="w-3.5 h-3.5" />
                    隐藏图钉
                  </>
                ) : (
                  <>
                    <Eye className="w-3.5 h-3.5" />
                    显示图钉
                  </>
                )}
              </button>
              
              {currentPagePins.length > 0 && (
                <button
                  onClick={handleClearAll}
                  className="flex items-center gap-1 text-slate-400 hover:text-rose-500 transition-colors font-semibold py-1.5 cursor-pointer"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                  清空本页标注
                </button>
              )}
            </div>
            
            {/* Primary Actions */}
            <div className="flex gap-2">
              <button
                onClick={handleExportMarkdown}
                disabled={currentPagePins.length === 0}
                className={`flex-1 py-2 px-3 rounded-xl text-xs font-bold transition-all flex items-center justify-center gap-1.5 cursor-pointer ${
                  currentPagePins.length > 0 
                    ? 'bg-blue-600 hover:bg-blue-700 text-white shadow-md shadow-blue-500/10' 
                    : 'bg-slate-100 text-slate-400 cursor-not-allowed border border-slate-200/50'
                }`}
              >
                <Download className="w-3.5 h-3.5" />
                导出 Markdown 清单
              </button>
              
              <button
                onClick={() => setIsEnabled(false)}
                className="py-2 px-3 border border-slate-200 hover:bg-slate-50 text-slate-700 text-xs font-bold rounded-xl transition-colors cursor-pointer"
              >
                关闭
              </button>
            </div>
          </div>
        )}
      </div>
    </>
  );
};

export default FeedbackOverlay;
